declare const _default: {
    onblur: string;
    onchange: string;
    oncontextmenu: string;
    onfocus: string;
    oninput: string;
    oninvalid: string;
    onreset: string;
    onsearch: string;
    onselect: string;
    onsubmit: string;
    onkeydown: string;
    onkeypress: string;
    onkeyup: string;
    onclick: string;
    ondblclick: string;
    onmousedown: string;
    onmousemove: string;
    onmouseout: string;
    onmouseover: string;
    onmouseup: string;
    onwheel: string;
    onanimationend: string;
    onanimationstart: string;
    ondrag: string;
    ondragend: string;
    ondragenter: string;
    ondragexit: string;
    ondragleave: string;
    ondragover: string;
    ondragstop: string;
    ondrop: string;
};
export default _default;
